### List all [GET]

List all categories.

+ Response 200 (application/json)
    + Attributes (array, fixed)
        + (object)
            + id: 1 (number, required)
            + image_id: 293202f9d9f7f4 (string, required)
            + name: cooking (string, required)
            + created_at: `2019-10-18-10:05:55` (string, required)
            + updated_at: `2019-10-18-10:05:55` (string, required)
